baseurl                 = "/"
languageCode            = "en-us"
title                   = "Zhiyao Chen"
theme                   = "onepagescroll"
pygmentsStyle           = "monokai"         # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = "xxx"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/zchen.ico"
    homepage            = "↑ Top"                       # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    footerText          = "Zhiyao Chen © 2018"

# Metadata
    description         = "Works by Zhiyao Chen"        # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "icon_large.jpg"              # Image that shows on Twitter cards and OpenGraph links

[[params.siteMenu]]
    link = "/info"
    text = "info"

[[params.siteMenu]]
    link = "/contact"
    text = "contact"
    